export const translations = {
  en: {
    'logo': 'Logo',
    'claim': 'claim',
    'bloodstone': 'bloodstone',
    'summonBeast': 'Summon Beast',
    'summonQuantity': 'Summon Quantity',
    'currentBeasts': 'Current Beasts',
    'warriorCapacity': 'Total Maximum Warriors Capacity',
    'filterCapacity': 'Filter By Capacity',
    'all': 'All',
    'welcome': 'Nadodo is watching',
    'play': 'Play',
    'market': 'Market',
    'getBloodstone': 'Get $Bloodstone',
    'howToPlay': 'How To Play',
    'social': 'Social',
    'privacy': 'Privacy',
    'beasts': 'Beasts',
    'warriors': 'Warriors',
    'legions': 'Legions',
    'hunt': 'Hunt',
    'usefulLinks': 'Useful Links',
    'buyBlst': 'Buy $BLST',
    'help': 'Help',
    'pancakeswap': 'Pancakeswap',
    'whitepaper': 'Whitepaper',
    'twitter': 'Twitter',
    'telegram': 'Telegram',
    'discord': 'Discord',
    'policy': 'Policy',
    'createLegion': 'Create Legion',
    'loadingBeasts': 'Loading Beasts ...',
    'summonWarrior': 'Summon Warrior',
    'currentWarriors': 'Current Warriors',
    'attackPower': 'Total Attack Power',
    'loadingWarriors': 'Loading Warriors ...',
    'filterAP': 'Filter By AP',
    'nameLegion': 'Name Your Legion',
    'loadingTitle': 'Loading Beasts & Warriors...',
    'createLegionsBtn': 'Create legion with ',
    'btnBackToLegions': 'Back to your Legions',
    'updateLegion': 'Update Legion',
    'updateNamePlaceholder': 'Name of the legion that is being updated',
    'yourOldLegionAP': 'Your existing legion has ',
    'dragAndDropInst': 'Drag/Drop beasts/warriors',
    'availableWarrior': 'Available Warriors',
    'availableBeast': 'Available Beasts',
    'currentLegion': 'Current Legions',
    'totalAp': 'Total AP',
    'top3Legions': 'Top 3 Legions',
    'lowest': 'Lowest',
    'highest': 'Highest',
    'sortByAp': 'Sort By AP',
    'filterByAp': 'Filter By AP',
    'huntStatus': 'Hunt Status',
    'green': 'Green',
    'orange': 'Orange',
    'red': 'Red',
    'hideWeakLegions': 'Hide Weak Legions',
    'buyMoreSupply': 'Buy More Supplies',
    'loadingMonsters': 'Loading Monsters ...'
  },
  es: {
    'logo': 'Logotipo',
    'claim': 'reclamo',
    'bloodstone': 'bloodstone',
    'summonBeast': 'Invocar Bestia',
    'summonQuantity': 'Cantidad de invocación',
    'currentBeasts': 'Bestias Actuales',
    'warriorCapacity': 'Capacidad máxima total de guerreros',
    'filterCapacity': 'Filtrar por capacidad',
    'all': 'Todo',
    'welcome': 'Nadodo está mirando',
    'play': 'Play',
    'market': 'Mercado',
    'getBloodstone': 'Obtener $Bloodstone',
    'howToPlay': 'Cómo jugar',
    'social': 'Social',
    'privacy': 'Privacidad',
    'beasts': 'bestias',
    'warriors': 'guerreros',
    'legions': 'legiones',
    'hunt': 'cazar',
    'pancakeswap': 'Pancakeswap',
    'whitepaper': 'documento técnico',
    'twitter': 'twitter',
    'telegram': 'Telegrama',
    'discord': 'Discordia',
    'policy': 'Política',
    'createLegion': 'Crear una legión',
    'loadingBeasts': 'Cargando bestias...',
    'summonWarrior': 'Summon Warrior',
    'currentWarriors': 'Current Warriors',
    'attackPower': 'Total Attack Power',
    'loadingWarriors': 'Loading Warriors ...',
    'filterLevel': 'Filter By Level',
    'filterAP': 'Filter By AP',
    'nameLegion': 'Name Your Legion',
    'loadingTitle': 'Loading Beasts & Warriors...',
    'createLegionsBtn': 'Create legion with ',
    'btnBackToLegions': 'Back to your Legions',
    'updateLegion': 'Update Legion',
    'updateNamePlaceholder': 'Name of the legion that is being updated',
    'yourOldLegionAP': 'Your existing legion has ',
    'dragAndDropInst': 'Drag/Drop beasts/warriors',
    'availableWarrior': 'Available Warriors',
    'availableBeast': 'Available Beasts',
    'currentLegion': 'Current Legions',
    'totalAp': 'Total AP',
    'top3Legions': 'Top 3 Legions',
    'lowest': 'Lowest',
    'highest': 'Highest',
    'sortByAp': 'Sort By AP',
    'filterByAp': 'Filter By AP',
    'huntStatus': 'Hunt Status',
    'green': 'Green',
    'orange': 'Orange',
    'red': 'Red',
    'hideWeakLegions': 'Hide Weak Legions',
    'usefulLinks': 'Useful Links',
    'loadingMonsters': 'Loading Monsters ...'
  }
}
