export const translations = {
  logo: {
    en: "Logo",
    es: "Logo",
    cn: "标识",
    pt: "Logotipo",
    tr: "Logo",
    ru: "Логотип",
    fr: "Logo",
    de: "Logo",
    pl: "Logo",
    ph: "Logo",
  },
  claim: {
    en: "claim",
    es: "afirmar",
    cn: "宣称",
    pt: "afirmação",
    tr: "iddia",
    ru: "требовать",
    fr: "Réclamer",
    de: "claim",
    pl: "prawo",
    ph: "paghahabol",
  },
  bloodstone: {
    en: "bloodstone",
    es: "bloodstone",
    cn: "bloodstone",
    pt: "bloodstone",
    tr: "bloodstone",
    ru: "bloodstone",
    fr: "bloodstone",
    de: "bloodstone",
    pl: "bloodstone",
    ph: "bloodstone",
  },
  summonBeast: {
    en: "Summon Beasts",
    es: "Invocar Bestia",
    cn: "召唤兽",
    pt: "Invocar Besta",
    tr: "Canavar Çağır",
    ru: "Призвать зверя",
    fr: "Invoquer une bête",
    de: "Roep Beest op",
    pl: "Przyzwanie bestii",
    ph: "Tawagin ang Hayop",
  },
  summonQuantity: {
    en: "Summon Quantity",
    es: "Cantidad de invocación",
    cn: "召唤数量",
    pt: "Quantidade de invocação",
    tr: "Çağırma Miktarı",
    ru: "Количество призыва",
    fr: "Quantité d'invocation",
    de: "Oproep hoeveelheid",
    pl: "Ilość przywołań",
    ph: "Summon Quantity",
  },
  currentBeasts: {
    en: "Current Beasts",
    es: "Bestias actuales",
    cn: "当前的野兽",
    pt: "Bestas Atuais",
    tr: "Mevcut Canavarlar",
    ru: "Текущие звери",
    fr: "Bêtes actuelles",
    de: "Huidige beesten",
    pl: "Obecne bestie",
    ph: "Kasalukuyang Hayop",
  },
  warriorCapacity: {
    en: "Total Capacity of All Beasts",
    es: "Capacidad máxima total de guerreros",
    cn: "最大勇士总容量",
    pt: "Capacidade Máxima Total de Guerreiros",
    tr: "Toplam Maksimum Savaşçı Kapasitesi",
    ru: "Общая максимальная вместимость воинов",
    fr: "Capacité totale maximale des guerriers",
    de: "Totale maximale krijgerscapaciteit",
    pl: "Całkowita maksymalna pojemność wojowników",
    ph: "Kabuuang Pinakamataas na Kapasidad ng Mga Mandirigma",
  },
  filterCapacity: {
    en: "Filter By Capacity",
    es: "Filtrar por capacidad",
    cn: "按容量过滤",
    pt: "Filtrar por capacidade",
    tr: "Kapasiteye Göre Filtrele",
    ru: "Фильтровать по емкости",
    fr: "Filtrer par capacité",
    de: "Filteren op capaciteit",
    pl: "Filtruj według pojemności",
    ph: "Salain Ayon sa Kapasidad",
  },
  all: {
    en: "All",
    es: "Todo",
    cn: "全部",
    pt: "Tudo",
    tr: "Herşey",
    ru: "Все",
    fr: "Tout",
    de: "Allemaal",
    pl: "Wszystkie",
    ph: "Lahat",
  },
  welcome: {
    en: "Nadodo is watching",
    es: "Nadodo está mirando",
    cn: "纳多多在看",
    pt: "Nadodo está assistindo",
    tr: "Nadodo izliyor",
    ru: "Надодо наблюдает",
    fr: "Nadodo regarde",
    de: "Nadodo kijkt mee",
    pl: "Nadodo patrzy",
    ph: "Nadodo is watching",
  },
  play: {
    en: "Play",
    es: "Tocar",
    cn: "玩",
    pt: "Toque",
    tr: "Oyna",
    ru: "Играть в",
    fr: "Jouer",
    de: "Toneelstuk",
    pl: "Bawić się",
    ph: "Maglaro",
  },
  market: {
    en: "Market",
    es: "Mercado",
    cn: "市场",
    pt: "Mercado",
    tr: "Market",
    ru: "Рынок",
    fr: "Marché",
    de: "Markt",
    pl: "Rynek",
    ph: "Merkado",
  },
  getBloodstone: {
    en: "Get $Bloodstone",
    es: "Consigue $Bloodstone",
    cn: "获得 $Bloodstone",
    pt: "Obtenha $Bloodstone",
    tr: "$Bloodstone al",
    ru: "Получите $Bloodstone",
    fr: "Obtenez $Bloodstone",
    de: "Krijg $Bloodstone",
    pl: "Zdobądź $Bloodstone",
    ph: "Kumuha ng $Bloodstone",
  },
  howToPlay: {
    en: "How To Play",
    es: "Cómo jugar",
    cn: "怎么玩",
    pt: "Como jogar",
    tr: "Nasıl oynanır",
    ru: "Как играть",
    fr: "Comment jouer",
    de: "Hoe te spelen",
    pl: "Jak grać",
    ph: "Paano laruin",
  },
  social: {
    en: "Social",
    es: "Social",
    cn: "社会的",
    pt: "Social",
    tr: "Sosyal",
    ru: "Социальное",
    fr: "Social",
    de: "sociaal",
    pl: "Społeczny",
    ph: "Sosyal",
  },
  privacy: {
    en: "Privacy",
    es: "Intimidad",
    cn: "隐私",
    pt: "Privacidade",
    tr: "Mahremiyet",
    ru: "Конфиденциальность",
    fr: "Vie privée",
    de: "Privacy",
    pl: "Prywatność",
    ph: "Pagkapribado",
  },
  beasts: {
    en: "Beasts",
    es: "Ganado",
    cn: "野兽",
    pt: "Bestas",
    tr: "canavarlar",
    ru: "Звери",
    fr: "Bêtes",
    de: "beesten",
    pl: "Bestie",
    ph: "mga hayop",
  },
  warriors: {
    en: "Warriors",
    es: "guerreros",
    cn: "勇士",
    pt: "Guerreiros",
    tr: "savaşçılar",
    ru: "Воины",
    fr: "Guerriers",
    de: "krijgers",
    pl: "Wojownicy",
    ph: "Mga mandirigma",
  },
  legions: {
    en: "Legions",
    es: "legiones",
    cn: "军团",
    pt: "Legiões",
    tr: "Lejyonlar",
    ru: "Легионы",
    fr: "Légions",
    de: "legioenen",
    pl: "Legiony",
    ph: "Legion",
  },
  hunt: {
    en: "Hunt",
    es: "Cazar",
    cn: "打猎",
    pt: "Caçar",
    tr: "Avlanmak",
    ru: "Охота",
    fr: "Chasser",
    de: "Jacht",
    pl: "Polowanie",
    ph: "Manghuli",
  },
  usefulLinks: {
    en: "Useful Links",
    es: "Enlaces útiles",
    cn: "有用的链接",
    pt: "Links Úteis",
    tr: "kullanışlı bağlantılar",
    ru: "Полезные ссылки",
    fr: "Liens utiles",
    de: "handige links",
    pl: "Przydatne linki",
    ph: "Mga Kapaki-pakinabang na Link",
  },
  buyBlst: {
    en: "Buy $BLST",
    es: "Comprar $BLST",
    cn: "购买 $BLST",
    pt: "Compre $BLST",
    tr: "$BLST satın al",
    ru: "Купить $BLST",
    fr: "Acheter $BLST",
    de: "Koop $BLST",
    pl: "Kup $BLST",
    ph: "Bumili ng $BLST",
  },
  help: {
    en: "Help",
    es: "Ayudar",
    cn: "帮助",
    pt: "Ajuda",
    tr: "Yardım",
    ru: "Помощь",
    fr: "Aider",
    de: "Helpen",
    pl: "Pomoc",
    ph: "Tulong",
  },
  pancakeswap: {
    en: "Pancakeswap",
    es: "Pancakeswap",
    cn: "Pancakeswap",
    pt: "Pancakeswap",
    tr: "Pancakeswap",
    ru: "Pancakeswap",
    fr: "Pancakeswap",
    de: "Pancakeswap",
    pl: "Pancakeswap",
    ph: "Pancakeswap",
  },
  whitepaper: {
    en: "Whitepaper",
    es: "Papel blanco",
    cn: "白皮书",
    pt: "Papel branco",
    tr: "Beyaz kağıt",
    ru: "Белая бумага",
    fr: "Papier blanc",
    de: "Wit papier",
    pl: "Biały papier",
    ph: "Puting papel",
  },
  twitter: {
    en: "Twitter",
    es: "Gorjeo",
    cn: "推特",
    pt: "Twitter",
    tr: "heyecan",
    ru: "Твиттер",
    fr: "Twitter",
    de: "Twitter",
    pl: "Świergot",
    ph: "Twitter",
  },
  telegram: {
    en: "Telegram",
    es: "Telegrama",
    cn: "电报",
    pt: "Telegrama",
    tr: "Telgraf",
    ru: "Телеграмма",
    fr: "Télégramme",
    de: "Telegram",
    pl: "Telegram",
    ph: "Telegrama",
  },
  discord: {
    en: "Discord",
    es: "Discordia",
    cn: "不和谐",
    pt: "Discórdia",
    tr: "anlaşmazlık",
    ru: "Раздор",
    fr: "Discorde",
    de: "Meningsverschil",
    pl: "Niezgoda",
    ph: "Hindi pagkakasundo",
  },
  policy: {
    en: "Policy",
    es: "Política",
    cn: "政策",
    pt: "Política",
    tr: "Politika",
    ru: "Политика",
    fr: "Politique",
    de: "Het beleid",
    pl: "Polityka",
    ph: "Patakaran",
  },
  madeWith: {
    en: "Made with",
    es: "Hecho con",
    cn: "用制作",
    pt: "Feito com",
    tr: "tarafından yapılmıştır",
    ru: "Сделано с",
    fr: "Fait avec",
    de: "Gemaakt met",
    pl: "Wykonane z",
    ph: "Ginawa gamit ang",
  },
  cryptoAgency: {
    en: "by Crypto Games Agency",
    es: "por Crypto Games Agency",
    cn: "Crypto Games Agency",
    pt: "pela Crypto Games Agency",
    tr: "ile Crypto Games Agency",
    ru: "агентством Crypto Games",
    fr: "par Crypto Games Agency",
    de: "door Crypto Games Agency",
    pl: "przez Crypto Games Agency",
    ph: "ng Crypto Games Agency",
  },
  createLegion: {
    en: "Create Legion",
    es: "crear legión",
    cn: "创建军团",
    pt: "Criar Legião",
    tr: "Lejyon Oluştur",
    ru: "Создать Легион",
    fr: "Créer une légion",
    de: "Legioen maken",
    pl: "Stwórz legion",
    ph: "Lumikha ng Legion",
  },
  loadingBeasts: {
    en: "Loading Beasts ...",
    es: "Cargando Bestias ...",
    cn: "装载野兽...",
    pt: "Carregando Bestas ...",
    tr: "Canavarlar Yükleniyor ...",
    ru: "Загрузка зверей ...",
    fr: "Chargement des bêtes ...",
    de: "Beesten laden ...",
    pl: "Ładowanie bestii ...",
    ph: "Naglo-load ng mga Hayop ...",
  },
  summonWarrior: {
    en: "Summon Warriors",
    es: "Invocar guerrero",
    cn: "召唤战士",
    pt: "Invocar Guerreiro",
    tr: "Savaşçılar Yükleniyor ...",
    ru: "Призыв воин",
    fr: "Invoquer un guerrier",
    de: "Roep krijger op",
    pl: "Przywołaj wojownika",
    ph: "Tawagin ang mandirigma",
  },
  currentWarriors: {
    en: "Current Warriors",
    es: "Guerreros actuales",
    cn: "现在的勇士",
    pt: "Guerreiros atuais",
    tr: "Mevcut Savaşçılar",
    ru: "Текущие воины",
    fr: "Guerriers actuels",
    de: "Huidige krijgers",
    pl: "Obecni wojownicy",
    ph: "Mga Kasalukuyang Mandirigma",
  },
  attackPower: {
    en: "Total Attack Power",
    es: "Poder de ataque total",
    cn: "总攻击力",
    pt: "Poder de Ataque Total",
    tr: "Toplam Saldırı Gücü",
    ru: "Общая сила атаки",
    fr: "Puissance d'attaque totale",
    de: "Totale aanvalskracht",
    pl: "Całkowita siła ataku",
    ph: "Kabuuang Lakas ng Pag-atake",
  },
  loadingWarriors: {
    en: "Loading Warriors ...",
    es: "Cargando guerreros ...",
    cn: "加载勇士 ...",
    pt: "Carregando Guerreiros ...",
    tr: "Savaşçılar Yükleniyor ...",
    ru: "Загрузка воинов ...",
    fr: "Chargement des guerriers ...",
    de: "Krijgers laden",
    pl: "Ładowanie wojowników ...",
    ph: "Naglo-load ng mga Mandirigma ...",
  },
  nameLegion: {
    en: "Name Your Legion",
    es: "Nombra tu legión",
    cn: "命名你的军团",
    pt: "Nomeie sua Legião",
    tr: "Lejyonunuzu Adlandırın",
    ru: "Назовите свой легион",
    fr: "Nommez votre Légion",
    de: "Noem je legioen",
    pl: "Nazwij swój legion",
    ph: "Pangalanan ang Iyong Legion",
  },
  loadingTitle: {
    en: "Loading Warriors & Beasts...",
    es: "Cargando Guerreros y Bestias...",
    cn: "加载野兽和战士...",
    pt: "Carregando Guerreiros e Bestas ...",
    tr: "Canavarlar ve Savaşçılar Yükleniyor...",
    ru: "Загрузка зверей и воинов...",
    fr: "Chargement des bêtes et des guerriers...",
    de: "Warriors & Beasts laden...",
    pl: "Ładowanie wojowników i bestii...",
    ph: "load ng mga Mandirigma at Hayop...",
  },
  createLegionsBtn: {
    en: "Create legion with ",
    es: "Crea legión con ",
    cn: "创建军团 ",
    pt: "Crie legião com ",
    tr: "ile lejyon oluştur ",
    ru: "Создайте легион с ",
    fr: "Créez une légion avec ",
    de: "Maak legioen met ",
    pl: "Stwórz legion za pomocą ",
    ph: "Lumikha ng legion gamit ang ",
  },
  btnBackToLegions: {
    en: "Back to your Legions",
    es: "Crea legión con",
    cn: "回到你的军团",
    pt: "De volta às suas legiões",
    tr: "Lejyonlarınıza geri dönün",
    ru: "Назад к своим легионам",
    fr: "Retournez à vos légions",
    de: "Terug naar je legioenen",
    pl: "Powrót do twoich legionów",
    ph: "Bumalik sa iyong Legions",
  },
  updateLegion: {
    en: "Update Legion",
    es: "Actualizar Legión",
    cn: "更新军团",
    pt: "Atualizar Legião",
    tr: "Lejyonu Güncelle",
    ru: "Обновить Легион",
    fr: "Mettre à jour la Légion",
    de: "Legioen bijwerken",
    pl: "Aktualizuj Legion",
    ph: "I-update ang Legion",
  },
  updateNamePlaceholder: {
    en: "Name of the legion that is being updated",
    es: "Nombre de la legión que se está actualizando",
    cn: "正在更新的军团名称",
    pt: "Nome da legião que está sendo atualizada",
    tr: "Güncellenmekte olan lejyonun adı",
    ru: "Название обновляемого легиона",
    fr: "Nom de la légion qui est mise à jour",
    de: "Naam van het legioen dat wordt bijgewerkt",
    pl: "Nazwa legionu, który jest aktualizowany",
    ph: "Pangalan ng legion na ina-update",
  },
  yourOldLegionAP: {
    en: "Your existing legion has ",
    es: "Su legión existente tiene ",
    cn: "你现有的军团有 ",
    pt: "Sua legião existente tem ",
    tr: "Mevcut lejyonunuzda ",
    ru: "Ваш существующий легион имеет ",
    fr: "Votre légion actuelle a ",
    de: "Uw bestaande legioen heeft ",
    pl: "Twój istniejący legion ma ",
    ph: "Ang iyong kasalukuyang legion ay mayroon",
  },
  dragAndDropInst: {
    en: "Drag/Drop beasts/warriors",
    es: "Arrastrar/soltar bestias/guerreros",
    cn: "拖放野兽/战士",
    pt: "Arrastar/soltar bestas/guerreiros",
    tr: "Canavarları/savaşçıları Sürükle/Bırak",
    ru: "Перетащите/бросьте зверей/воинов",
    fr: "Glisser/déposer des bêtes/guerriers",
    de: "Drag/Drop beesten/krijgers",
    pl: "Przeciągnij/upuść bestie/wojownicy",
    ph: "I-drag/I-drop ang mga hayop/mandirigma",
  },
  availableWarrior: {
    en: "Available Warriors",
    es: "Guerreros disponibles",
    cn: "可用的勇士",
    pt: "Guerreiros Disponíveis",
    tr: "Mevcut Savaşçılar",
    ru: "Доступные воины",
    fr: "Guerriers disponibles",
    de: "Beschikbare krijgers",
    pl: "Dostępni wojownicy",
    ph: "Available na Warriors",
  },
  availableBeast: {
    en: "Available Beasts",
    es: "Bestias disponibles",
    cn: "可用的野兽",
    pt: "Bestas Disponíveis",
    tr: "Mevcut Canavarlar",
    ru: "Доступные звери",
    fr: "Bêtes disponibles",
    de: "Beschikbare beesten",
    pl: "Dostępne bestie",
    ph: "Magagamit na mga Hayop",
  },
  currentLegion: {
    en: "Current Legions",
    es: "Legiones actuales",
    cn: "当前军团",
    pt: "Legiões atuais",
    tr: "Mevcut Lejyonlar",
    ru: "Текущие легионы",
    fr: "Légions actuelles",
    de: "huidige legioenen",
    pl: "Obecne Legiony",
    ph: "Kasalukuyang Legion",
  },
  totalAp: {
    en: "Total AP",
    es: "AP totales",
    cn: "总 AP",
    pt: "PA total",
    tr: "Toplam AP",
    ru: "Всего AP",
    fr: "AP totaux",
    de: "Totaal AP",
    pl: "Razem AP",
    ph: "Kabuuang AP",
  },
  top3Legions: {
    en: "Top 3 Legions",
    es: "Las 3 mejores legiones",
    cn: "前 3 名军团",
    pt: "3 principais legiões",
    tr: "En İyi 3 Lejyon",
    ru: "3 лучших легиона",
    fr: "Top 3 des Légions",
    de: "Top 3 legioenen",
    pl: "3 najlepsze legiony",
    ph: "Nangungunang 3 Legion",
  },
  lowest: {
    en: "Lowest",
    es: "más bajo",
    cn: "最低",
    pt: "Mais baixo",
    tr: "En düşük",
    ru: "Самый низкий",
    fr: "Le plus bas",
    de: "laagste",
    pl: "Najniższy",
    ph: "Pinakamababa",
  },
  highest: {
    en: "Highest",
    es: "más alto",
    cn: "最高",
    pt: "Altíssima",
    tr: "En yüksek",
    ru: "Наибольший",
    fr: "Plus haut",
    de: "hoogste",
    pl: "Najwyższy",
    ph: "Pinakamataas",
  },
  sortByAp: {
    en: "Sort By AP",
    es: "Ordenar por AP",
    cn: "按 AP 排序",
    pt: "Classificar por AP",
    tr: "AP'ye göre sırala",
    ru: "Сортировать по точке доступа",
    fr: "Trier par point d'accès",
    de: "Sorteren op AP",
    pl: "Sortuj według AP",
    ph: "Pagbukud-bukurin Ayon sa AP",
  },
  filterByAp: {
    en: "Filter By AP",
    es: "Filtrar por AP",
    cn: "按 AP 过滤",
    pt: "Filtrar por AP",
    tr: "AP'ye göre filtrele",
    ru: "Фильтровать по точке доступа",
    fr: "Filtrer par point d'accès",
    de: "Filteren op AP",
    pl: "Filtruj według AP",
    ph: "I-filter Ayon sa AP",
  },
  huntStatus: {
    en: "Hunt Status",
    es: "Estado de caza",
    cn: "狩猎状态",
    pt: "Status de busca",
    tr: "Av Durumu",
    ru: "Статус охоты",
    fr: "Statut de chasse",
    de: "Huntstatus",
    pl: "Status polowania",
    ph: "Katayuan ng Hunt",
  },
  green: {
    en: "Green",
    es: "Verde",
    cn: "绿",
    pt: "Verde",
    tr: "Yeşil",
    ru: "Зеленый",
    fr: "Vert",
    de: "Groente",
    pl: "Zielony",
    ph: "Berde",
  },
  orange: {
    en: "Orange",
    es: "naranja",
    cn: "橘子",
    pt: "laranja",
    tr: "Portakal",
    ru: "апельсин",
    fr: "Orange",
    de: "Oranje",
    pl: "Pomarańczowy",
    ph: "Kahel",
  },
  red: {
    en: "Red",
    es: "rojo",
    cn: "红色的",
    pt: "vermelho",
    tr: "kırmızı",
    ru: "красный",
    fr: "rouge",
    de: "rood",
    pl: "czerwony",
    ph: "Pula",
  },
  hideWeakLegions: {
    en: "Hide Weak Legions",
    es: "Ocultar legiones débiles",
    cn: "隐藏弱小军团",
    pt: "Esconder Legiões Fracas",
    tr: "Zayıf Lejyonları Gizle",
    ru: "Скрыть слабые легионы",
    fr: "Cachez les légions faibles",
    de: "Verberg zwakke legioenen",
    pl: "Ukryj słabe legiony",
    ph: "Itago ang Mahina Legions",
  },
  buySupply: {
    en: "Buy Supplies",
    es: "Comprar más suministros",
    cn: "购买更多用品",
    pt: "Comprar mais suprimentos",
    tr: "Daha Fazla Malzeme Satın Alın",
    ru: "Купите больше расходных материалов",
    fr: "Acheter plus de fournitures",
    de: "Koop meer benodigdheden",
    pl: "Kup więcej materiałów eksploatacyjnych!",
    ph: "Bumili ng Higit pang Supplies",
  },
  filterLevel: {
    en: "Filter By Level",
    es: "Filtrar por nivel",
    cn: "按级别过滤",
    pt: "Filtrar por nível",
    tr: "Seviyeye Göre Filtrele",
    ru: "Фильтровать по уровню",
    fr: "Filtrer par niveau",
    de: "Filteren op niveau",
    pl: "Filtruj według poziomu",
    ph: "I-filter Ayon sa Antas",
  },
  loadingMonsters: {
    en: "Loading Monsters...",
    es: "Cargando Monstruos...",
    cn: "加载怪物...",
    pt: "Carregando Monstros...",
    tr: "Canavarlar Yükleniyor...",
    ru: "Загрузка монстров...",
    fr: "Chargement des monstres...",
    de: "Monsters laden...",
    pl: "Ładowanie potworów...",
    ph: "Naglo-load ng mga Halimaw...",
  },
  yourInventory: {
    en: "YOUR INVENTORY",
    es: "SU INVENTARIO",
    cn: "您的库存",
    pt: "SEU INVENTÁRIO",
    tr: "ENVANTERİNİZ",
    ru: "ВАШ ИНВЕНТАРЬ",
    fr: "VOTRE INVENTAIRE",
    de: "UW INVENTARIS",
    pl: "TWÓJ Ekwipunek",
    ph: "IYONG IMBENTARYO",
  },
  availableLegions: {
    en: "Available legions to hunt",
    es: "Legiones disponibles para cazar",
    cn: "可用军团狩猎",
    pt: "Legiões disponíveis para caçar",
    tr: "Avlanmak için mevcut lejyonlar",
    ru: "Доступные легионы для охоты",
    fr: "Légions disponibles pour chasser",
    de: "Beschikbare legioenen om op te jagen",
    pl: "Dostępne legiony do polowania",
    ph: "Magagamit na mga legion upang manghuli",
  },
  waitingTimeToHunt: {
    en: "Waiting time until next hunt",
    es: "Tiempo de espera hasta la próxima cacería",
    cn: "等待下一次狩猎的时间",
    pt: "Tempo de espera até a próxima caçada",
    tr: "Bir sonraki av için bekleme süresi",
    ru: "Время ожидания до следующей охоты",
    fr: "Temps d'attente jusqu'à la prochaine chasse",
    de: "Wachttijd tot de volgende jacht",
    pl: "Czas oczekiwania do następnego polowania",
    ph: "Oras ng paghihintay hanggang sa susunod na pamamaril",
  },
  yourMaxAp: {
    en: "AP of top legion",
    es: "AP de la legión superior",
    cn: "顶级军团AP",
    pt: "AP da legião superior",
    tr: "üst lejyonun AP'si",
    ru: "AP высшего легиона",
    fr: "AP de la légion supérieure",
    de: "AP van top legioen",
    pl: "AP najwyższego legionu",
    ph: "AP ng nangungunang legion",
  },
  unClaimed: {
    en: "Unclaimed $BLST",
    es: "$BLST no reclamado",
    cn: "无人认领的 $BLST",
    pt: "$BLST não reivindicado",
    tr: "Talep edilmemiş $BLST",
    ru: "Невостребованные $BLST",
    fr: "$BLST non réclamé",
    de: "Niet-geclaimde $BLST",
    pl: "Nieodebrane $BLST",
    ph: "Hindi na-claim na $BLST",
  },
  claimTax: {
    en: "If you'd claim now, you'd pay",
    es: "Si reclamaras ahora, pagarías",
    cn: "如果您现在提出索赔，您将支付",
    pt: "Se você reivindicasse agora, você pagaria",
    tr: "Şimdi talep etseydin, öderdin",
    ru: "Если бы вы требовали сейчас, вы бы заплатили",
    fr: "Si vous réclamiez maintenant, vous paieriez",
    de: "Als je nu zou claimen, zou je betalen",
    pl: "Jeśli złożysz wniosek teraz, zapłacisz",
    ph: "Kung mag-claim ka ngayon, magbabayad ka",
  },
  claimTaxVal: {
    en: "$BLST tax",
    es: "impuesto $BLST",
    cn: "$BLST 税",
    pt: "Imposto $BLST",
    tr: "$BLST vergisi",
    ru: "$BLST налог",
    fr: "Taxe $BLST",
    de: "$BLST belasting",
    pl: "$BLST podatek",
    ph: "buwis sa $BLST",
  },
  taxDaysLeft: {
    en: "Tax Days Left",
    es: "Días de impuestos restantes",
    cn: "剩余纳税天数",
    pt: "Dias fiscais restantes",
    tr: "Vergi Günleri Kaldı",
    ru: "Осталось налоговых дней",
    fr: "Jours d'impôt restants",
    de: "Resterende belastingdagen",
    pl: "Pozostałe dni podatkowe",
    ph: "Tax Days Natitira",
  },
  BLSTInYourWallet: {
    en: "$BLST in Your Wallet",
    es: "$BLST en su billetera",
    cn: "钱包中的 $BLST",
    pt: "$BLST em sua carteira",
    tr: "Cüzdanınızda $BLST",
    ru: "$BLST в вашем кошельке",
    fr: "$BLST dans votre portefeuille",
    de: "$BLST in uw portemonnee",
    pl: "$BLST w Twoim portfelu",
    ph: "$BLST sa Iyong Wallet",
  },
  takeAction: {
    en: "TAKE ACTION",
    es: "Tomar acción",
    cn: "采取行动",
    pt: "Tome uma atitude",
    tr: "Harekete geç",
    ru: "Действовать",
    fr: "Passer à l'action",
    de: "Actie ondernemen",
    pl: "Podejmij działanie",
    ph: "Gumawa ng aksyon",
  },
  takeActionSummonBeastQuantity: {
    en: "SUMMON BEAST QUANTITY",
    es: "Invocar cantidad de bestias",
    cn: "召唤兽数量",
    pt: "Invocar quantidade de besta",
    tr: "Canavar Miktarı Çağır",
    ru: "Призыв зверя Количество",
    fr: "Quantité d'invocation de bête",
    de: "Roep Beest Hoeveelheid op",
    pl: "Ilość Przyzwania Bestii",
    ph: "Ipatawag ang Dami ng Hayop",
  },
  takeActionSummonWarriorQuantity: {
    en: "SUMMON WARRIOR QUANTITY",
    es: "Invocar cantidad de guerreros",
    cn: "召唤战士数量",
    pt: "Invocar Guerreiro Quantidade",
    tr: "Savaşçı Miktarı Çağır",
    ru: "Призыв Воина Количество",
    fr: "Quantité d'invocation de guerrier",
    de: "Roep Warrior-hoeveelheid op",
    pl: "Ilość przywołania wojownika",
    ph: "Ipatawag ang Dami ng Mandirigma",
  },
  takeActionCreateLegion: {
    en: "CREATE LEGION",
    es: "Comprar Bestias",
    cn: "购买野兽",
    pt: "Comprar Bestas",
    tr: "Canavar satın al",
    ru: "Купить зверей",
    fr: "Acheter des bêtes",
    de: "Beesten kopen",
    pl: "Kup bestie",
    ph: "Bumili ng mga Hayop",
  },
  takeActionMassHunt: {
    en: "Mass Hunt",
    es: "Caza masiva",
    cn: "大规模狩猎",
    pt: "Caça em massa",
    tr: "toplu av",
    ru: "Массовая охота",
    fr: "Chasse de masse",
    de: "massa jacht",
    pl: "Masowe polowanie",
    ph: "Mass Hunt",
  },
  takeActionBuyBeasts: {
    en: "Beasts Market",
    es: "Mercado de bestias",
    cn: "野兽市场",
    pt: "Mercado de feras",
    tr: "Canavar Pazarı",
    ru: "Рынок зверей",
    fr: "Marché aux bêtes",
    de: "Beestenmarkt",
    pl: "Targ Bestii",
    ph: "Beasts Market",
  },
  takeActionBuyWarriors: {
    en: "Warriors Market",
    es: "Mercado de guerreros",
    cn: "勇士市场",
    pt: "Mercado de guerreiros",
    tr: "Savaşçı Pazarı",
    ru: "Рынок воинов",
    fr: "Marché des guerriers",
    de: "Warriors markt",
    pl: "Rynek wojowników",
    ph: "Merkado ng mga mandirigma",
  },
  takeActionBuyLegions: {
    en: "Legions Market",
    es: "Mercado de las legiones",
    cn: "军团市场",
    pt: "Mercado das Legiões",
    tr: "Lejyon Pazarı",
    ru: "Рынок легионов",
    fr: "Marché des légions",
    de: "Legioenen Markt",
    pl: "Rynek Legionów",
    ph: "Legions Market",
  },
  takeActionPoocoin: {
    en: "Poocoin Chart",
    es: "Gráfico de Poocoin",
    cn: "Poocoin 图表",
    pt: "Gráfico Poocoin",
    tr: "Poocoin Tablosu",
    ru: "График Poocoin",
    fr: "Graphique Pocoin",
    de: "Poocoin-grafiek",
    pl: "Wykres Poocoin",
    ph: "Chart ng Poocoin",
  },
  takeActionBuyBlst: {
    en: "BUY $BLST",
    es: "COMPRAR $ BLST",
    cn: "购买$BLST",
    pt: "COMPRE $BLST",
    tr: "$BLST SATIN AL",
    ru: "КУПИТЬ $BLST",
    fr: "ACHETER $BLST",
    de: "KOOP $BLST",
    pl: "KUP $BLST",
    ph: "BUMILI ng $BLST",
  },
  yourAchievements: {
    en: "YOUR ACHIEVEMENTS",
    es: "Sus logros",
    cn: "你的成就",
    pt: "Suas conquistas",
    tr: "Başarılarınız",
    ru: "Ваши достижения",
    fr: "Vos réalisations",
    de: "Jouw prestaties",
    pl: "Twoje osiągnięcia",
    ph: "Ang iyong mga nagawa",
  },
  readInstructionsInWhitePaper: {
    en: "READ INSTRUCTIONS IN WHITEPAPER",
    es: "Lea las instrucciones en el documento técnico",
    cn: "阅读白皮书中的说明",
    pt: "Leia as instruções no whitepaper",
    tr: "Teknik İncelemedeki Talimatları Okuyun",
    ru: "Прочтите инструкции в Техническом документе",
    fr: "Lire les instructions dans le livre blanc",
    de: "Lees de instructies in de whitepaper",
    pl: "Przeczytaj instrukcje w białej księdze",
    ph: "Basahin ang Mga Tagubilin sa Whitepaper",
  },
  summonWarriorSuccessful: {
    en: "Summon Warriors successfully! If you see your all warriors, please click this!",
    es: "¡Invoca guerreros con éxito! Si ves a todos tus guerreros, ¡haz clic aquí!",
    cn: "成功召唤勇士！如果你看到你所有的战士，请点击这里！",
    pt: "Convoque Guerreiros com sucesso! Se você vir todos os seus guerreiros, clique aqui!",
    tr: "Savaşçıları başarıyla çağır! Tüm savaşçılarınızı görüyorsanız, lütfen buna tıklayın!",
    ru: "Призыв воинов успешно! Если вы видите всех своих воинов, нажмите здесь!",
    fr: "Invoquez des guerriers avec succès ! Si vous voyez tous vos guerriers, veuillez cliquer ici !",
    de: "Roep Warriors succesvol op! Als je al je krijgers ziet, klik dan hier!",
    pl: "Przywołaj wojowników pomyślnie! Jeśli widzisz wszystkich swoich wojowników, kliknij to!",
    ph: "Matagumpay na ipatawag ang mga Mandirigma! Kung nakikita mo ang iyong lahat ng mga mandirigma, mangyaring i-click ito!",
  },
  summonBeastSuccessful: {
    en: "Summon Beasts successfully! If you see your all beasts, please click this!",
    es: "¡Invoca bestias con éxito! Si ves todas tus bestias, ¡haz clic aquí!",
    cn: "召唤兽成功！如果你看到你所有的野兽，请点击这里！",
    pt: "Convocar Bestas com sucesso! Se você vir todos os seus animais, por favor clique aqui!",
    tr: "Canavarları başarıyla çağır! Tüm canavarlarınızı görüyorsanız, lütfen buna tıklayın!",
    ru: "Призыв Зверей успешно! Если вы видите всех своих зверей, пожалуйста, нажмите здесь!",
    fr: "Invoquez des bêtes avec succès ! Si vous voyez toutes vos bêtes, veuillez cliquer dessus !",
    de: "Roep Beesten succesvol op! Als je al je beesten ziet, klik dan hier!",
    pl: "Przywołaj bestie pomyślnie! Jeśli widzisz wszystkie swoje bestie, kliknij to!",
    ph: "Matagumpay na ipatawag ang mga Hayop! Kung nakikita mo ang lahat ng iyong mga hayop, mangyaring i-click ito!",
  },
  summoningBeasts: {
    en: "Summoning Beasts...",
    es: "Bestias de invocación...",
    cn: "Invocation de bêtes...",
    pt: "Invocando Bestas...",
    tr: "Çağıran Canavarlar...",
    ru: "Призыв зверей...",
    fr: "Invocation de bêtes...",
    de: "Beesten oproepen...",
    pl: "Przyzywanie Bestii...",
    ph: "Pagtawag ng mga Hayop...",
  },
  nadodoWatching: {
    en: "NADODO IS WATCHING",
    es: "Nadodo está mirando",
    cn: "纳多多在看",
    pt: "Nadodo está assistindo",
    tr: "Nadodo izliyor",
    ru: "Надодо наблюдает",
    fr: "Nadodo regarde",
    de: "Nadodo kijkt mee",
    pl: "Nadodo patrzy",
    ph: "Nadodo is watching",
  },
  summoningWarriors: {
    en: "Summoning Warriors...",
    es: "Invocando guerreros...",
    cn: "召唤战士...",
    pt: "Invocando Guerreiros...",
    tr: "Savaşçıları Çağırmak...",
    ru: "Призыв воинов...",
    fr: "Invoquer des guerriers...",
    de: "Strijders oproepen...",
    pl: "Przyzywanie wojowników...",
    ph: "Pagtawag ng mga Mandirigma...",
  },
  marketplaceTax: {
    en: "Marketplace Tax",
    es: "Impuesto del Mercado",
    cn: "市场税",
    pt: "Imposto do mercado",
    tr: "Pazar Vergisi",
    ru: "Торговый налог",
    fr: "Taxe de marché",
    de: "Marktplaatsbelasting",
    pl: "Podatek od rynku",
    ph: "Buwis sa Marketplace",
  },
  huntTax: {
    en: "Hunt Tax",
    es: "Impuesto de caza",
    cn: "=狩猎税",
    pt: "Taxa de caça",
    tr: "av vergisi",
    ru: "Охотничий налог",
    fr: "Taxe de chasse",
    de: "jachtbelasting",
    pl: "Podatek od polowania",
    ph: "Buwis sa Hunt",
  },
  buyTax: {
    en: "Buy Tax",
    es: "Comprar impuestos",
    cn: "购买税",
    pt: "Comprar imposto",
    tr: "Vergi Satın Al",
    ru: "Купить налог",
    fr: "Taxe d'achat",
    de: "Koop belasting",
    pl: "Kup podatek",
    ph: "Bumili ng Buwis",
  },
  sellTax: {
    en: "Sell Tax",
    es: "Impuesto de venta",
    cn: "销售税",
    pt: "Imposto sobre vendas",
    tr: "Satış Vergisi",
    ru: "Налог на продажу",
    fr: "Taxe de vente",
    de: "Verkoop belasting",
    pl: "Sprzedaj podatek",
    ph: "Magbenta ng Buwis",
  },
  legionDamagePerHunt: {
    en: "Legion Damage Per Hunt",
    es: "Daño de legión por cacería",
    cn: "每次狩猎的军团伤害",
    pt: "Dano da Legião por Caçada",
    tr: "Av Başına Lejyon Hasarı",
    ru: "Урон Легиона за охоту",
    fr: "Dégâts de légion par chasse",
    de: "Legioenschade per jacht",
    pl: "Obrażenia legionu na polowanie",
    ph: "Legion Damage Bawat Hunt",
  },
  summoningFee: {
    en: "Summoning Fee",
    es: "Cuota de convocatoria",
    cn: "召唤费",
    pt: "taxa de invocação",
    tr: "çağrı ücreti",
    ru: "плата за вызов",
    fr: "frais de convocation",
    de: "oproepingsvergoeding",
    pl: "Opłata za przywołanie",
    ph: "ummoning Fee",
  },
  SuppliesFee14Hunts: {
    en: "Supplies Fee for 14 Hunts",
    es: "Tarifa de suministros para 14 cacerías",
    cn: "14 次狩猎的用品费",
    pt: "Taxa de suprimentos para 14 caçadas",
    tr: "14 Av için Malzeme Ücreti",
    ru: "Плата за припасы за 14 охот",
    fr: "Frais de fournitures pour 14 chasses",
    de: "Benodigdhedenvergoeding voor 14 jachten",
    pl: "Opłata za zapasy za 14 polowań",
    ph: "Bayad sa Supplies para sa 14 na Hunt",
  },
  SuppliesFee28Hunts: {
    en: "Supplies Fee for 28 Hunts",
    es: "Tarifa de suministros para 28 cacerías",
    cn: "28 次狩猎的用品费",
    pt: "Taxa de suprimentos para 28 caçadas",
    tr: "28 Av için Malzeme Ücreti",
    ru: "Плата за припасы за 28 охот",
    fr: "Frais de fournitures pour 28 chasses",
    de: "Benodigdhedenvergoeding voor 28 jachten",
    pl: "Opłata za zapasy za 28 polowań",
    ph: "Bayad sa Supplies para sa 28 na Hunt",
  },
  RewardPool: {
    en: "Reward Pool",
    es: "Grupo de recompensas",
    cn: "奖励池",
    pt: "Pool de recompensas",
    tr: "Ödül Havuzu",
    ru: "Пул вознаграждений",
    fr: "Pool de récompenses",
    de: "Beloningspool",
    pl: "Pula nagród",
    ph: "Pool ng Gantimpala",
  },
  ReservePool: {
    en: "Reserve Pool",
    es: "Grupo de reserva",
    cn: "储备池",
    pt: "Reserva Pool",
    tr: "Rezerv Havuzu",
    ru: "Резервный бассейн",
    fr: "Piscine de réserve",
    de: "Reserveer zwembad",
    pl: "Rezerwuj pulę",
    ph: "Reserve Pool",
  },
  LiquidityPool: {
    en: "Liquidity Pool",
    es: "Fondo de liquidez",
    cn: "流动资金池",
    pt: "Reserva de Liquidez",
    tr: "Likidite Havuzu",
    ru: "Пул ликвидности",
    fr: "Pool de liquidités",
    de: "Liquiditeitspool",
    pl: "Pula płynności",
    ph: "Liquidity Pool",
  },
  buyingSupplies: {
    en: "Buying Supplies...",
    es: "Compra de suministros...",
    cn: "购买用品...",
    pt: "Compra de suprimentos...",
    tr: "Malzeme Satın Alma...",
    ru: "Покупка расходных материалов...",
    fr: "Acheter des fournitures...",
    de: "Benodigdheden kopen...",
    pl: "Kupowanie materiałów eksploatacyjnych...",
    ph: "Pagbili ng Supplies...",
  },
  loadingLegions: {
    en: "Loading Legions...",
    es: "Cargando Legiones...",
    cn: "装载军团...",
    pt: "Carregando Legiões...",
    tr: "Lejyonları Yükleme...",
    ru: "Загрузка легионов...",
    fr: "Chargement des légions...",
    de: "Legioenen laden...",
    pl: "Ładowanie legionów...",
    ph: "Naglo-load ng Legions...",
  },
  noMintedLegion: {
    en: "You need to create a legion first to start hunting!",
    es: "¡Necesitas crear una legión primero para comenzar a cazar!",
    cn: "您需要先创建一个军团才能开始狩猎！",
    pt: "Você precisa criar uma legião primeiro para começar a caçar!",
    tr: "Avlanmaya başlamak için önce bir lejyon oluşturmanız gerekiyor!",
    ru: "Вам нужно сначала создать легион, чтобы начать охоту!",
    fr: "Vous devez d'abord créer une légion pour commencer à chasser !",
    de: "Je moet eerst een legioen creëren om te kunnen jagen!",
    pl: "Aby rozpocząć polowanie, musisz najpierw stworzyć legion!",
    ph: "Kailangan mo munang lumikha ng isang legion upang simulan ang pangangaso!",
  },
  marketplace: {
    en: "Marketplace",
    es: "Mercado",
    cn: "市场",
    pt: "Mercado",
    tr: "pazar yeri",
    ru: "Торговая площадка",
    fr: "Marché",
    de: "Marktplaats",
    pl: "Rynek",
    ph: "Marketplace",
  },
  sortBy: {
    en: "Sort By",
    es: "Ordenar por",
    cn: "排序方式",
    pt: "Ordenar por",
    tr: "Göre sırala",
    ru: "Сортировать по",
    fr: "Trier par",
    de: "Sorteer op",
    pl: "Sortuj według",
    ph: "Pagbukud-bukurin Ayon",
  },
  confirm: {
    en: "Confirm",
    es: "Confirmar",
    cn: "确认",
    pt: "confirme",
    tr: "Teyit etmek",
    ru: "Подтверждать",
    fr: "Confirmer",
    de: "Bevestigen",
    pl: "Potwierdzać",
    ph: "Kumpirmahin",
  },
  huntTime: {
    en: "Hunting Time!",
    es: "Tiempo de caza!",
    cn: "狩猎时间！",
    pt: "Hora da caça!",
    tr: "Av Zamanı!",
    ru: "Время охоты!",
    fr: "Temps de chasse !",
    de: "Jagen tijd!",
    pl: "Czas polowania!",
    ph: "Oras ng Pangangaso!",
  },
  huntTimeSubtitle1: {
    en: "Your legion is now attacking the monster:",
    es: "Tu legión ahora está atacando al monstruo:",
    cn: "你的军团现在正在攻击怪物：",
    pt: "Sua legião agora está atacando o monstro:",
    tr: "Lejyonunuz şimdi canavara saldırıyor:",
    ru: "Теперь ваш легион атакует монстра:",
    fr: "Votre légion attaque maintenant le monstre :",
    de: "Je legioen valt nu het monster aan:",
    pl: "Twój legion atakuje teraz potwora:",
    ph: "Inaatake na ngayon ng iyong legion ang halimaw:",
  },
  congratulation: {
    en: "Congratulations!",
    es: "Felicidades!",
    cn: "恭喜！",
    pt: "Parabéns!",
    tr: "Tebrikler!",
    ru: "Поздравляем!",
    fr: "Toutes nos félicitations!",
    de: "Gefeliciteerd!",
    pl: "Gratulacje!",
    ph: "Binabati kita!",
  },
  congSubtitle1: {
    en: "You defeated this monster!",
    es: "Has derrotado a este monstruo!",
    cn: "你打败了这个怪物！",
    pt: "Você derrotou este monstro!",
    tr: "Bu canavarı yendin!",
    ru: "Вы победили этого монстра!",
    fr: "Vous avez vaincu ce monstre !",
    de: "Je hebt dit monster verslagen!",
    pl: "Pokonałeś tego potwora!",
    ph: "Natalo mo ang halimaw na ito!",
  },
  congSubtitle3: {
    en: "To win you need to roll equal or less than:",
    es: "Para ganar necesitas tirar igual o menos que:",
    cn: "要获胜，您需要滚动等于或小于：",
    pt: "Para ganhar você precisa rolar igual ou menor que:",
    tr: "Kazanmak için aşağıdakilere eşit veya daha az yuvarlamanız gerekir:",
    ru: "Чтобы выиграть, вам нужно выбросить меньше или равно:",
    fr: "Pour gagner, vous devez obtenir un résultat égal ou inférieur à :",
    de: "Om te winnen moet je gelijk of minder gooien dan:",
    pl: "Aby wygrać, musisz wyrzucić równą lub mniejszą niż:",
    ph: "Upang manalo kailangan mong gumulong katumbas o mas mababa sa:",
  },
  continue: {
    en: "Continue",
    es: "Continuar",
    cn: "继续",
    pt: "Continuar",
    tr: "Devam et",
    ru: "Продолжать",
    fr: "Continuez",
    de: "Doorgaan",
    pl: "Kontyntynuj",
    ph: "Magpatuloy",
  },
  defeatTitle: {
    en: "Better Luck Next Time...",
    es: "Mejor suerte la próxima vez...",
    cn: "下次好运...",
    pt: "Mais sorte da próxima vez...",
    tr: "Bir Dahaki Sefere Daha İyi Şanslar...",
    ru: "Повезет в следующий раз...",
    fr: "Plus de chance la prochaine fois...",
    de: "Volgende keer beter...",
    pl: "Więcej szczęścia następnym razem...",
    ph: "Baka palarin sa susunod...",
  },
  defeatSubtitle1: {
    en: "Your legion did not succeed in getting Bloodstoone from this monster, this time",
    es: "Tu legión no logró obtener Bloodstoone de este monstruo, esta vez",
    cn: "这次你们军团没能从这个怪物身上得到血石",
    pt: "Sua legião não conseguiu obter Bloodstoone deste monstro, desta vez",
    tr: "Lejyonunuz bu sefer bu canavardan Bloodstone almayı başaramadı.",
    ru: "На этот раз вашему легиону не удалось получить Бладстоун из этого монстра.",
    fr: "Votre légion n'a pas réussi à obtenir Bloodstoone de ce monstre, cette fois",
    de: "Je legioen is er deze keer niet in geslaagd om Bloodstoone van dit monster te krijgen",
    pl: "Waszemu legionowi tym razem nie udało się zdobyć Krwawnika z tego potwora",
    ph: "Hindi nagtagumpay ang iyong legion na makuha ang Bloodstoone mula sa halimaw na ito, sa pagkakataong ito",
  },
  defeatSubtitle2: {
    en: "To win you need to roll equal or less than:",
    es: "Para ganar necesitas tirar igual o menos que:",
    cn: "要获胜，您需要滚动等于或小于：",
    pt: "Para ganhar você precisa rolar igual ou menor que:",
    tr: "Kazanmak için aşağıdakilere eşit veya daha az yuvarlamanız gerekir:",
    ru: "Чтобы выиграть, вам нужно выбросить меньше или равно:",
    fr: "Pour gagner, vous devez obtenir un résultat égal ou inférieur à :",
    de: "Om te winnen moet je gelijk of minder gooien dan:",
    pl: "Aby wygrać, musisz wyrzucić równą lub mniejszą niż:",
    ph: "Upang manalo kailangan mong gumulong katumbas o mas mababa sa:",
  },
  yourRollTitle: {
    en: "Your roll is",
    es: "tu rollo es",
    cn: "你的卷是",
    pt: "Seu rolo é",
    tr: "senin rulon",
    ru: "Ваш рулон",
    fr: "Votre rouleau est",
    de: "Jouw rol is",
    pl: "Twoja rolka to",
    ph: "Ang iyong rolyo ay",
  },
  showMyWarrior: {
    en: "Show Only My Warriors",
    es: "Mostrar solo mis guerreros",
    cn: "只显示我的勇士",
    pt: "Mostrar apenas meus guerreiros",
    tr: "Yalnızca Savaşçılarımı Göster",
    ru: "Показать только моих воинов",
    fr: "Afficher uniquement mes guerriers",
    de: "Toon alleen mijn krijgers",
    pl: "Pokaż tylko moich wojowników",
    ph: "Ipakita Lamang ang Aking Mga Mandirigma",
  },
  pleaseWait: {
    en: "Please Wait...",
    es: "Espere por favor...",
    cn: "请稍等...",
    pt: "Por favor, aguarde...",
    tr: "Lütfen bekleyin...",
    ru: "Пожалуйста, подождите...",
    fr: "S'il vous plaît, attendez...",
    de: "Wacht alsjeblieft...",
    pl: "Proszę czekać...",
    ph: "Mangyaring Maghintay...",
  },
  first: {
    en: "First",
    es: "Primero",
    cn: "第一的",
    pt: "Primeiro",
    tr: "Öncelikle",
    ru: "Первый",
    fr: "Première",
    de: "Eerst",
    pl: "Pierwszy",
    ph: "Una",
  },
  last: {
    en: "Last",
    es: "Último",
    cn: "最后的",
    pt: "Durar",
    tr: "Son",
    ru: "Прошлой",
    fr: "Dernier",
    de: "Laatst",
    pl: "Trwać",
    ph: "Huli",
  },
  previous: {
    en: "Previous",
    es: "Anterior",
    cn: "以前的",
    pt: "Anterior",
    tr: "Öncesi",
    ru: "Предыдущий",
    fr: "Précédent",
    de: "Vorig",
    pl: "Poprzedni",
    ph: "Nakaraang",
  },
  next: {
    en: "Next",
    es: "Próximo",
    cn: "下一个",
    pt: "Próximo",
    tr: "Sonraki",
    ru: "Следующий",
    fr: "Suivant",
    de: "Volgende",
    pl: "Następny",
    ph: "Susunod",
  },
  showMyBeast: {
    en: "Show Only My Beasts",
    es: "Mostrar solo mis bestias",
    cn: "只显示我的野兽",
    pt: "Mostrar apenas minhas feras",
    tr: "Sadece Canavarlarımı Göster",
    ru: "Показывать только моих зверей",
    fr: "Afficher uniquement mes bêtes",
    de: "Toon alleen mijn beesten",
    pl: "Pokaż tylko moje bestie",
    ph: "Ipakita ang Aking Mga Hayop Lamang",
  },
  showMyLegion: {
    en: "Show Only My Legions",
    es: "Mostrar solo mis legiones",
    cn: "仅显示我的军团",
    pt: "Mostrar apenas minhas legiões",
    tr: "Yalnızca Lejyonlarımı Göster",
    ru: "Показать только мои легионы",
    fr: "Afficher uniquement mes légions",
    de: "Toon alleen mijn legioenen",
    pl: "Pokaż tylko moje legiony",
    ph: "Ipakita ang Aking Mga Legion Lamang",
  },
  filterByHunts: {
    en: "Filter By Hunts Left",
    es: "Filtrar por búsquedas restantes",
    cn: "按左侧狩猎过滤",
    pt: "Filtrar por buscas restantes",
    tr: "Soldaki Avlara Göre Filtrele",
    ru: "Фильтровать по оставшимся охотам",
    fr: "Filtrer par chasses restantes",
    de: "Filteren op jachten links",
    pl: "Filtruj według polowań w lewo",
    ph: "I-filter Ayon sa Hunts Kaliwa",
  },
  listOnMarketplace: {
    en: "List On Marketplace",
    es: "Lista al mercado",
    cn: "列表到市场",
    pt: "Listar para o mercado",
    tr: "Pazar Yeri Listesi",
    ru: "Список на рынок",
    fr: "Liste sur le marché",
    de: "Lijst naar marktplaats",
    pl: "Lista na rynku",
    ph: "Listahan Sa Marketplace",
  },
  congSubtitle2: {
    en: "You have been rewarded",
    es: "has sido recompensado",
    cn: "你得到了回报",
    pt: "Você foi recompensado",
    tr: "ödüllendirildin",
    ru: "Вы были вознаграждены",
    fr: "Vous avez été récompensé",
    de: "Je bent beloond",
    pl: "Zostałeś nagrodzony",
    ph: "Ikaw ay ginantimpalaan",
  },
  warriorMaster: {
    en: "Warrior Master",
    es: "Maestro guerrero",
    cn: "战士大师",
    pt: "Mestre Guerreiro",
    tr: "Savaşçı Usta",
    ru: "Мастер воинов",
    fr: "Maître guerrier",
    de: "krijger meester",
    pl: "Mistrz wojownika",
    ph: "Maestro ng mandirigma",
  },
  beastMaster: {
    en: "Beast Master",
    es: "Maestro de bestias",
    cn: "野兽大师",
    pt: "Mestre das Bestas",
    tr: "Canavarustası",
    ru: "Повелитель зверей",
    fr: "Maître des bêtes",
    de: "Beest Meester",
    pl: "Mistrz Bestii",
    ph: "Hayop na Guro",
  },
  legionMaster: {
    en: "Legion Master",
    es: "Maestro de la legión",
    cn: "军团长",
    pt: "Mestre da Legião",
    tr: "Lejyon Ustası",
    ru: "Мастер легиона",
    fr: "Maître de la Légion",
    de: "Legioen Meester",
    pl: "Mistrz Legionu",
    ph: "Legion Master",
  },
  monsterConqueror: {
    en: "Monster Conqueror",
    es: "Conquistador de monstruos",
    cn: "怪物征服者",
    pt: "Conquistador de Monstros",
    tr: "Canavar Fatihi",
    ru: "Завоеватель монстров",
    fr: "Conquérant de monstre",
    de: "Monster Veroveraar",
    pl: "Zdobywca potworów",
    ph: "Halimaw na mananakop",
  },
  "King/Queen": {
    en: "King/Queen of Nicah",
    es: "Rey/Reina Nica",
    cn: "国王/王后尼卡",
    pt: "Rei/Rainha Nicah",
    tr: "Kral/Kraliçe Nicah",
    ru: "Король/Королева Ника",
    fr: "Roi/Reine Nica",
    de: "Koning/Koningin Nicha",
    pl: "Król/Królowa Nicha",
    ph: "Hari/Reyna Nicah",
  },
  warriorMasterEx: {
    en: "Own a level 6 warrior",
    es: "Ten un guerrero de nivel 6",
    cn: "拥有一名6级战士",
    pt: "Possuir um guerreiro de nível 6",
    tr: "6. seviye bir savaşçıya sahip ol",
    ru: "Иметь воина 6 уровня",
    fr: "Posséder un guerrier de niveau 6",
    de: "Bezit een krijger van niveau 6",
    pl: "Posiadaj wojownika na poziomie 6",
    ph: "Pagmamay-ari ng level 6 na mandirigma",
  },
  beastMasterEx: {
    en: "Own a beast with 20 capacity",
    es: "Posee una bestia con 20 de capacidad.",
    cn: "拥有一只20容量的野兽",
    pt: "Possuir uma fera com capacidade de 20",
    tr: "20 kapasiteli bir canavara sahip olun",
    ru: "Собственный зверь с 20 вместимостью",
    fr: "Posséder une bête avec une capacité de 20",
    de: "Bezit een beest met een capaciteit van 20",
    pl: "Posiadaj bestię o pojemności 20",
    ph: "Pagmamay-ari ng isang hayop na may 20 kapasidad",
  },
  legionMasterEx: {
    en: "Own 10 legions of 30,000+ AP",
    es: "Posee 10 legiones de 30,000+ AP",
    cn: "拥有10个军团30,000+ AP",
    pt: "Possui 10 legiões de 30.000+ AP",
    tr: "30.000'den fazla AP'ye sahip 10 lejyona sahip olun",
    ru: "Иметь 10 легионов по 30 000+ AP",
    fr: "Posséder 10 légions de 30 000+ AP",
    de: "Bezit 10 legioenen van meer dan 30.000 AP",
    pl: "Posiadaj 10 legionów po 30 000+ AP",
    ph: "Pagmamay-ari ng 10 legions ng 30,000+ AP",
  },
  monsterConquerorEx: {
    en: "Win a hunt of Monster 23",
    es: "Gana una cacería de Monster 23",
    cn: "赢得一场怪物 23 的追捕",
    pt: "Vença uma caçada ao Monstro 23",
    tr: "Canavar 23 avını kazan",
    ru: "Выиграйте охоту на монстра 23",
    fr: "Gagnez une chasse au monstre 23",
    de: "Win een jacht op Monster 23",
    pl: "Wygraj polowanie na Potwora 23",
    ph: "Manalo ng isang pamamaril ng Monster 23",
  },
  "King/QueenEx": {
    en: "Win a hunt of Monster 24",
    es: "Gana una cacería de Monster 24",
    cn: "赢得一场怪物 24 的追捕",
    pt: "Vença uma caçada ao Monstro 24",
    tr: "Canavar 24 avını kazan",
    ru: "Выиграйте охоту на монстра 24",
    fr: "Gagnez une chasse au monstre 24",
    de: "Win een jacht op Monster 24",
    pl: "Wygraj polowanie na Potwora 24",
    ph: "Manalo ng isang pamamaril ng Monster 24",
  },
  sell: {
    en: "Sell",
    es: "Vender",
    cn: "卖",
    pt: "Vender",
    tr: "Satmak",
    ru: "Продавать",
    fr: "Vendre",
    de: "Verkopen",
    pl: "Sprzedać",
    ph: "Ibenta",
  },
  noBeastFilter: {
    en: "No beasts with this capacity. Summon some more!",
    es: "No hay bestias con esta capacidad. ¡Convoca a algunos más!",
    cn: "没有这种能力的野兽。再召唤一些！",
    pt: "Nenhuma besta com essa capacidade. Convoque mais alguns!",
    tr: "Bu kapasitede canavar yok. Biraz daha çağır!",
    ru: "Нет зверей с такой способностью. Позовите еще!",
    fr: "Aucune bête avec cette capacité. Invoquez-en d'autres !",
    de: "Geen beesten met deze capaciteit. Roep nog wat op!",
    pl: "Żadnych bestii z taką zdolnością. Przywołaj więcej!",
    ph: "Walang mga hayop na may ganitong kapasidad. Magpatawag pa!",
  },
  noWarriorFilter: {
    en: "No warriors with this level/AP. Summon some more!",
    es: "No hay guerreros con este nivel/AP. ¡Convoca a algunos más!",
    cn: "没有这个级别/AP的战士。再召唤一些！",
    pt: "Nenhum guerreiro com este nível/AP. Convoque mais alguns!",
    tr: "Bu seviyeye/AP'ye sahip savaşçı yok. Biraz daha çağır!",
    ru: "Нет воинов с этим уровнем/AP. Позовите еще!",
    fr: "Aucun guerrier avec ce niveau/AP. Invoquez-en d'autres !",
    de: "Geen krijgers met dit niveau/AP. Roep nog wat op!",
    pl: "Żadnych wojowników z tym poziomem/AP. Przywołaj więcej!",
    ph: "Walang mga mandirigma na may ganitong antas/AP. Magpatawag pa!",
  },
  LongFeeToolTip: {
    en: "Fee to create your legion is ",
    es: "La tarifa para crear tu legión es",
    cn: "创建军团的费用是",
    pt: "A taxa para criar sua legião é",
    tr: "Lejyonunuzu oluşturma ücreti",
    ru: "Плата за создание своего легиона составляет",
    fr: "Les frais pour créer votre légion sont",
    de: "Kosten om je legioen te creëren is",
    pl: "Opłata za utworzenie legionu wynosi",
    ph: "Ang bayad sa paggawa ng iyong legion ay",
  },
  ShortFeeToolTip: {
    en: "Fee",
    es: "Tarifa",
    cn: "费用",
    pt: "Taxa",
    tr: "Ücret",
    ru: "Платеж",
    fr: "Frais",
    de: "Vergoeding",
    pl: "Opłata",
    ph: "Bayad",
  },
  feeToUpdate: {
    en: "Fee to update ",
    es: "Tarifa para actualizar ",
    cn: "更新费用 ",
    pt: "axa para atualizar ",
    tr: "Güncelleme ücreti ",
    ru: "Плата за обновление ",
    fr: "Frais de mise à jour ",
    de: "Kosten om te updaten ",
    pl: "Opłata za aktualizację ",
    ph: "Bayad sa pag-update ",
  },
  to: {
    en: "to",
    es: "para",
    cn: "到",
    pt: "para",
    tr: "ile",
    ru: "к",
    fr: "pour",
    de: "naar",
    pl: "do",
    ph: "sa",
  },
  create: {
    en: "Create",
    es: "Crear",
    cn: "创建",
    pt: "Crio",
    tr: "Yaratmak",
    ru: "Создавать",
    fr: "Créer",
    de: "Creëren",
    pl: "Tworzyć",
    ph: "Lumikha",
  },
  notEnoughBeasts: {
    en: "Not enough beasts",
    es: "No hay suficientes bestias",
    cn: "野兽不够",
    pt: "Não há animais suficientes",
    tr: "Yeterli canavar yok",
    ru: "Недостаточно зверей",
    fr: "Pas assez de bêtes",
    de: "Niet genoeg beesten",
    pl: "Za mało bestii",
    ph: "Hindi sapat ang mga hayop",
  },
  min: {
    en: "min",
    es: "min",
    cn: "分钟",
    pt: "min",
    tr: "dk",
    ru: "мин",
    fr: "min",
    de: "min",
    pl: "min",
    ph: "min",
  },
  needed: {
    en: "needed",
    es: "necesario",
    cn: "需要",
    pt: "necessário",
    tr: "gerekli",
    ru: "нужный",
    fr: "nécessaire",
    de: "nodig zijn",
    pl: "potrzebne",
    ph: "kailangan",
  },
  existingAPIs: {
    en: "Existing AP is",
    es: "El AP existente es",
    cn: "现有 AP 是",
    pt: "O AP existente é",
    tr: "Mevcut AP",
    ru: "Существующая точка доступа",
    fr: "Le point d'accès existant est",
    de: "Bestaande AP is",
    pl: "Istniejący AP to",
    ph: "Ang kasalukuyang AP ay",
  },
  update: {
    en: "Update",
    es: "Actualizar",
    cn: "更新",
    pt: "Atualizar",
    tr: "Güncelleme",
    ru: "Обновлять",
    fr: "Mettre à jour",
    de: "Bijwerken",
    pl: "Aktualizacja",
    ph: "Update",
  },
  base: {
    en: "Base",
    es: "Base",
    cn: "根据",
    pt: "Base",
    tr: "Temel",
    ru: "Основание",
    fr: "Base",
    de: "Baseren",
    pl: "Baza",
    ph: "Base",
  },
  bonus: {
    en: "Bonus",
    es: "Prima",
    cn: "奖金",
    pt: "Bônus",
    tr: "Bonus",
    ru: "Бонус",
    fr: "Prime",
    de: "Bonus",
    pl: "Premia",
    ph: "Bonus",
  },
  toWin: {
    en: "to Win",
    es: "ganar",
    cn: "赢",
    pt: "ganhar",
    tr: "kazanmak",
    ru: "побеждать",
    fr: "gagner",
    de: "winnen",
    pl: "wygrać",
    ph: "para manalo",
  },
  huntTransactionFailed: {
    en: "Transaction is failed, please try again!",
    es: "",
    cn: "",
    pt: "",
    tr: "",
    ru: "",
    fr: "",
    de: "",
    pl: "",
    ph: "",
  },
};
